config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get "/users", to: "users#index"
  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :stats
  has_many :skills
  has_many :spells
end

app/models/skill.rb
class stat < ApplicationRecord
  belongs_to :character
end

app/models/spell.rb
class stat < ApplicationRecord
  belongs_to :character
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :character
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'

  before_action :authenticate_user!

  def after_sign_in_path_for resource
    stored_location_for(resource) || characters_path
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new

    if @character.save
      redirect_to @character
    else
      render :new
    end
  end

  private

  def character_params
    params.require(:character).permit(
      :name,
      :char_class,
      :level,
      :race,
      :background,
      :alignment,
      :experience_points,
      :languages,
      :equipment,
      :features,
      :character_details,
      :copper,
      :silver,
      :gold,
      :platinum,
      :treasure
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  end

  def create
    if user = User.authenticate(params[:email], param[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
        redirect_to(session[:intended_url] || user)
        session[:intended_url] = nil
      else
        flash.now[:alert] = "Invalid email/password combination!"
        render :new
    end
  end

  def show
    response_with current_user
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/index.html.erb
<div class="characters">
  <div class="flex items-center justify-between flex-wrap flex-col md:flex-row py-5">
    <h2 class="text-2xl">You have <%= @characters.count %> characters.</h2>
    <%= link_to "Creat New Character", new_character_path, class: "button primary-btn" %>
  </div>
   <% @characters.each do |character| %>
    <div class="flex flex-col md:flex-row pb-8 md:pb-4 char_list">
      <div class="flex-wrap md:w-60">
        <a href="<%= character_path(character) %>" class="text-teal">
          <%= character.name %>
        </a>
      </div>
      <div class="flex-wrap w-60">
        <%= character.char_class %>
      </div>
      <div class="flex-wrap w-60">
        <%= character.race %>
      </div>
      <div class="flex-wrap w-20">
        <%= character.level %>
      </div>
      <div class="flex-wrap w-20 justify-end">
        <a href="/">Test</a>
      </div>
      <div class="flex-wrap w-20 content-end">
        <a href="/" class="warning-btn">Delete</a>
      </div>
    </div>
  <% end %>
</div>

app/views/characters/new.html.erb
<h2 class="text-2xl py-5">New Character</h2>
<div class="flex flex-col md:flex-row flex-wrap">
  <%= form_with model: @character do |form| %>
    <div class="flex-wrap">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
    <div class="flex-wrap">
      <%= form.label :class %><br>
      <%= form.text_field :class %>
    </div>
    <div>
      <%= form.label :level %><br>
      <%= form.number_field :level %>
    </div>
    <div>
      <%= form.label :race %><br>
      <%= form.text_field :race %>
    </div>
    <div>
      <%= form.label :background %><br>
      <%= form.text_area :background %>
    </div>
    <div>
      <%= form.label :experience_points %><br>
      <%= form.number_field :experience_points %>
    </div>
    <div>
      <%= form.label :languages %><br>
      <%= form.text_field :languages %>
    </div>
    <div>
      <%= form.label :equipment %><br>
      <%= form.text_field :equipment %>
    </div>
    <div>
      <%= form.label :features %><br>
      <%= form.text_field :features %>
    </div>
    <div>
      <%= form.label :character_details %><br>
      <%= form.text_area :character_details %>
    </div>
    <div>
      <%= form.label :copper %><br>
      <%= form.number_field :copper %>
    </div>
    <div>
      <%= form.label :silver %><br>
      <%= form.number_field :silver %>
    </div>
    <div>
      <%= form.label :gold %><br>
      <%= form.number_field :gold %>
    </div>
    <div>
      <%= form.label :platinum %><br>
      <%= form.number_field :platinum %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/characters/show.html.erb
<div class="container mx-auto px-4">
  <h1>
    <%= @character.name %>
  </h1>
  <p>Class:
    <%= @character.class %>
  </p>
  <p>Leve:
    <%= @character.level %>
  </p>
  <p>Race:
    <%= @character.race %>
  </p>
  <p> Background:
    <%= @character.background %>
  </p>
  <p>ALignment:
    <%= @character.alignment %>
  </p>
  <p>XP:
    <%= @character.experience_points %>
  </p>
  <p>Languages:
    <%= @character.languages %>
  </p>
  <p>Equipment:
    <%= @character.equipment %>
  </p>
  <p>Features:
    <%= @character.features %>
  </p>
  <p>Character details:
    <%= @character.character_details %>
  </p>
  <p>Monday</p>
  <p>Copper:
    <%= @character.copper %>
  </p>
  <p>Siler:
    <%= @character.silver %>
  </p>
  <p>Gold:
    <%= @character.gold %>
  </p>
  <p>Platinum:
    <%= @character.platinum %>
  </p>
  <p>Treasure:
    <%= @character.treasure %>
  </p>
</div>

app/views/home/index.html.erb
<% content_for :landing_page do %>
  <div class="flex landing-page">
    <div class="container px-4">
      <%= image_tag "logo2.png", alt: "blue and gray dragon logo", class: "mx-auto logo" %>
      <div class="text-white content">
        <h1>DnD Character Tracker</h1>
        <p>Where you'll never have to worry about where you left your character sheet or forget old characters.</p>
      </div>
      <div class="flex flex-row">
        <div class="flex mx-auto">
          <%= link_to 'Login', new_user_session_path, class: "button primary-btn" %>
          <%= link_to 'Register', new_user_registration_path, class: "button secondary-btn" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/show.html.erb
<div class="container mx-auto px-4">
  <h2 class="uppercase">Character List</h2>
</div>

app/views/layouts/_main_nav.html.erb
<nav class="flex items-center justify-between flex-wrap p-6 w-full z-10 top-0">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a class="text-white no-underline hover:text-white hover:no-underline" href="#">
        <span class="text-2xl pl-2"><i class="em em-grinning"></i>DnD Character Tracker</span>
      </a>
    </div>

    <div class="block lg:hidden">
      <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>

    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0 text-white" id="nav-content">
      <ul class="list-reset lg:flex justify-end flex-1 items-center">
        <li class="mr-3">
          <%= link_to "Characters", characters_path %>
        </li>
        <li class="mr-3">
          <% if current_user %>
          <%= link_to users_path do %>
        <% end %>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "block lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "block button primary-btn lg:inline-block lg:mt-0 hover:text-white" %>
          <%= link_to 'Register', new_user_registration_path, class: "block mt-4 mx-4 button secondary-btn lg:inline-block lg:mt-0 hover:text-white" %>
        <% end %>
        </li>
      </ul>
    </div>
</nav>


	<script>
		//Javascript to toggle the menu
		document.getElementById('nav-toggle').onclick = function(){
			document.getElementById("nav-content").classList.toggle("hidden");
		}
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnD Character Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;1,600&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="layout">
      <div class="nav-container md:mx-auto md:px-4">
        <%= render "layouts/main_nav" if current_user %>
      </div>
      <% if !current_user %>
        <%= yield :landing_page %>
      <% end %>
      <div id="main-content" class="container mx-auto px-4">
        <%= yield %>
      </div>
      <div class="flash-area">
        <% flash.each do |type, msg| %>
          <% if type == "notice" %>
            <div class="alert alert-success">
          <% elsif type == "alert" %>
            <div class="alert alert-danger">
          <% else %>
            <div class='alert alert-<%= "#{type}" %>'>
          <% end %>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <ul>
            <li>
              <%= msg %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>


    <script>
      //Javascript to toggle the menu
      document.getElementById('nav-toggle').onclick = function(){
        document.getElementById("nav-content").classList.toggle("hidden");
      }
    </script>
  </body>
</html>

app/views/users/index.html.erb
<div class="flex-col">
  <div>
    <%= current_user.email %>
  </div>
  <div>
    <%= link_to "Reset my password", user_password_path %>
  </div>
  <div>
    <%= button_to "Delete Account", user_registration_path, class: "bg-red-700" %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>